### ISSUE TITLE
As a user I would like to be able to create an account

### ISSUE THREAD

**Issue by currymich** [snfazal/ecommerce-app#12]

**Comment by snfazal** [comment]
1. need user model with password_digest and email as template
    - login partial needs a form for email and password
2. user controller 
3. post route in user's controller that can save the user to a db 
4. auth controller in angular 
5. signup partial with router.js states
6. body-parser used to get request info
7.

**Comment by currymich** [comment]
Resolved by commit 1f74722db320cfba76d540bf14df346cebbf214c
